### ISSUE TITLE
YouTube playlists

### ISSUE THREAD

**Issue by Udevelopment** [DominicMaas/SoundByte#10]
Hey.

How about abilities of creating playlists from YouTube music & connecting YouTube account (importing playlists from it to app)?

It's really would be cool. SoundCloud subscription not avalible in many countries => a lot of songs = 30 secs preview. YouTube have a lot of songs and avalible from any country.

**Comment by DominicMaas** [comment]
Hi,

I can think of two ways for doing this, let me know which one sounds the best.

## Method 1
User connects their YouTube account. Creating a playlist within SoundByte will create a YouTube playlist. Viewing YouTube playlists within SoundByte will display the actual playlists from your YouTube account.

## Method 2
Instead of having your SoundCloud playlists, or YouTube playlists, you can create SoundByte playlists. These playlists can contain songs from other platforms mixed together. The ability to import playlists from YouTube or SoundCloud will also be added.

Method 2 is more work, but I think might be a better idea in the long run. The real question becomes how do you store SoundByte playlists. Should the user use a SoundByte account, where these playlists are synced to an account (so you can access all your playlists on other devices and platforms), or should they be stored locally on the users device?

**Comment by Udevelopment** [comment]
"Method 2" sounds really-really cool.

I think, that SoundByte playlists should be synced across all devices, of course. 
It would be a good feature. For example: if user want to play playlist from PC on xbox one.
--
Also I wrote on your e-mail about translation. Look into if u want)

**Comment by DominicMaas** [comment]
Great. I'll start work on sign-in with a SoundByte account shortly.

**Comment by DominicMaas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improved YouTube Support](https://trello.com/c/7FaqPuev/5-improved-youtube-support)

**Comment by DominicMaas** [comment]
I added the ability to view and play YouTube playlists the other day. Creating YouTube playlist support will come in the next week.

As for creating SoundByte playlists, this might be pushed to 18.2 depending on how long everything else takes to implement.

**Comment by Udevelopment** [comment]
Great job, dude. 

Tnx for your app 😎
And I'm still ready to translate it to russian when you will ready with variables ;)

**Comment by DominicMaas** [comment]
Thanks! I'll close this issue (moving todo items to [here](https://github.com/DominicMaas/SoundByte/issues/17)). I'll probably start work on translation in the next release, but you can keep up to date [here](https://github.com/DominicMaas/SoundByte/issues/11).
